### Buscar todos os owners
GET http://localhost:3000/owners
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjEiLCJyb2xlIjoiYWRtaW4iLCJpYXQiOjE3ODQzODg5NzIsImV4cCI6MTc4NDM5OTc3Mn0.3ZSgGMX446cSYHIX4T-n5YAk3c40v2M0Bq3c1SUj6u0
Content-Type: application/json

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
			"emai": "jumamad@vitalvet.com",
			"password": "123456"
}

###
PATCH http://localhost:3000/appointments/accomplish/1001
Content-Type: application/json



###
DELETE http://localhost:3000/appointments/2
