### Buscar todos os owners
GET http://localhost:3000/appointments/1002
Content-Type: application/json

###
POST http://localhost:3000/appointments/
Content-Type: application/json

{
    "idAnimal": "1",
    "idDono": "1",
    "dataHora": "2025-03-01T14:00:00.000Z",
    "tipoExame": "Coleta",
    "status": "confirmado",
    "observacoesIniciais": "Animal brabo 2"
  }

###
PATCH http://localhost:3000/appointments/accomplish/1001
Content-Type: application/json



###
DELETE http://localhost:3000/appointments/2
