### Buscar todos os owners
GET http://localhost:3000/pets/name/Juma Beatriz
Content-Type: application/json

###
POST http://localhost:3000/pets
Content-Type: application/json

{
  "nome": "Lurdinha",
  "especie": "Gato",
  "raca": "Sem Raça",
  "idade": 3,
  "peso": 6,
  "sexo": "F",
  "idDono": "xPwq_G2"
}

###
PATCH http://localhost:3000/pets/W27Rb2y
Content-Type: application/json

{
    "peso":12
}


###
DELETE http://localhost:3000/pets/W27Rb2y
